### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Arisono** [nosqlcoco/springboot-weapp-demo#2]
麻烦可以写下如何配置服务器程序的简单说明吗，尤其是redis和mongdb数据库的配置方面的东西。

**Comment by nosqlcoco** [comment]
redis 和 mongodb 比较独立，你可以分别参考各自官网的默认配置进行修改，配置较多无法一一介绍。
redis config [https://redis.io/topics/config](url)
mongodb config [https://docs.mongodb.com/manual/reference/configuration-options/](url)
建议去官方网站系统的学习 redis 或 mongodb，这样比较全面。
